### ISSUE TITLE
ChromatiCraft saving it's pylon info, outside the world directory?

### ISSUE THREAD

**Issue by steelshot** [ReikaKalseki/Reika_Mods_Issues#1013]
So. i've reset my world to the same seed, built up my spawn, and returned to my previous base location to find a pylon in the middle of its old location, tried to remove it by deleting its value in pylonloc.dat and crystalnet.dat and removing the region file while the server was offline.

Turned it back on to find myself that pylon gone, but screen effects and the pylon compass still showing it and a new pylon spawning around 50 blocks away from it.

So i though ok, screw it, reverted back to a backup done before any editing to pylon data was done. So the original pylon is back. BUT WAIT, the new pylons are there now(from the new region), not the structures, but the effects and they being showed in the compass.

Shouldn't that happen? there is nothing in the world save that would have those new locations. I would like to know why and where this data is stored! I realy dont want to remake the world yet again because of this.

**Comment by steelshot** [comment]
Some of the newly generated pylons that should not exist at all 
![2016-07-01_09 34 55](https://cloud.githubusercontent.com/assets/5291010/16516291/3cc94e7e-3f6f-11e6-8298-fa76046a8906.png)
![2016-07-01_09 35 01](https://cloud.githubusercontent.com/assets/5291010/16516293/3ff615c8-3f6f-11e6-9f15-be6825ee2641.png)
![2016-07-01_09 35 11](https://cloud.githubusercontent.com/assets/5291010/16516295/4190c338-3f6f-11e6-8dc4-6f4d5348ac15.png)
![2016-07-01_09 35 35](https://cloud.githubusercontent.com/assets/5291010/16516296/4302e476-3f6f-11e6-8302-44067b92ea51.png)

**Comment by ReikaKalseki** [comment]
This may be related to #777, which now that that is fixed, probably fixes this too. Also, no, it is all saved to world data.

**Comment by steelshot** [comment]
hmm strange then, just a question if i removed the NBT values from the 2 dat files and removed the pylon structure with the node from the world, would that remove the pylon completely, ik its not a nice way of doing it, but sometimes the pylons just spawn in places you dont want them to be in, ik its not your problem as noone can predict where what will be?

**Comment by ReikaKalseki** [comment]
Just go to creative and break it.

**Comment by steelshot** [comment]
I have multiple times but, it keeps the screen effects and they are still shown in the compass, even after restarting the server multiple times

**Comment by ReikaKalseki** [comment]
You need to reboot the client as well. Relogging _should_ fix it, but as discussed above that had issues.
