### ISSUE TITLE
"air" NBT of Broadcast Repeater stays 0

### ISSUE THREAD

**Issue by Asgatoril** [ReikaKalseki/Reika_Mods_Issues#1508]
Hi,

in search for a solution for ignitediris and mine problem with Lumen Beacons, [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=29807) and [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=29842), I searched through the code and mapdata do find out why it isn't working.
In the end I found out, that the NBT-value for air on all tested beacons is 0, which stops the beacon from working.
This is even more suprising as the code for this check ([here](https://github.com/ReikaKalseki/ChromatiCraft/blob/789e6b5f2765ed162102bf7a751551ef7c549272/TileEntity/Networking/TileEntityCrystalBroadcaster.java)) always returns true, if c2 != 0 or crashes if c2 == 0. My guess is, that c1 and c2 in line 127 have been accidentally swapped.
Still this doesn't explain the strange NBT-value for air...
The other 3 required NBT values, interference, multi, and redstone, are like they should be.

Edit:
I just tried editing the air value ingame. As soon as I save them, the beacons work and transmit some Lumen until the value is updated some seconds later and the beacons stop working again.

**Comment by ReikaKalseki** [comment]
I think I fixed this recently; your description sounds familiar. Try again in v18.

**Comment by ignitediris** [comment]
Thanks for addressing this.

**Comment by Asgatoril** [comment]
I found a workaround for now:
If you use a mod like nbtedit ([1.7.10 version](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286750-in-game-nbtedit-edit-mob-spawners-attributes-in?page=74#c1487)) and change the value of air to 1 AND also make sure, that the chunk wont get un- or reloaded, e.g. with a chunk loader at each tower, then it works. 
Since I play on a small private server, this works quite well, as the chunks will only ever get unloaded if I restart the server. For singleplayer this may be a bit annoying since I guess, that you have to change the values again at each start of the game. Haven't tested singleplayer though.

**Comment by ignitediris** [comment]
A little strange to have air blocks be part of a structure but I suppose there are reasons...

I unfortunately have to restart my server every 8 hours or so. Luckily, I can wait for v18 as I am not progressed enough in my legitimate survival world to be affected by this.

**Comment by MineBartekSA** [comment]
I don't think so the v18 fixed this because i just upgraded it to v18b and tested if my beacons work on my server but it still don't work and whne i use command /printcrystalnet the the beacon structure is still false!
But my server have offline mode (because my friend don't want to buy Minecraft) so i tested it on singleplayer but it still don't work and when i use that command thne i once saw true but then when i try to connect them and test them it changed to false again! Of cource i was spawning Beacons on singleplayer.

**Comment by OvermindDL1** [comment]
> (because my friend don't want to buy Minecraft)

You do realize that by association saying such things is very bannable in many many areas?  Fair warning.  ^.^

**Comment by ReikaKalseki** [comment]
Additionally, if you want to be helpful, you have to be clear and coherent, not posting an entire paragraph of sentence that repeatedly contradicts itself.

**Comment by MineBartekSA** [comment]
First of all i deleted that comment.
Second, i apologize for it.

But i've done some tests on Lumen Beacons this time on clean pack only with ChromatiCraft, NET and ProjectE (for faster traveling), and the Beacons finnaly work for me!

![2017-08-19_14 03 03](https://user-images.githubusercontent.com/19757593/29486803-c6acde7e-84ee-11e7-900d-82ebc3886629.png)

It works!

But when i wanted to try on my bigger modpack, on my map then i find out that Lumen Beacons don't work in RFTools Dims.
But when i try on Overworld then it works.

**Comment by ReikaKalseki** [comment]
The crystal network does not work in most dimensions. This is not a bug.
