### ISSUE TITLE
[CrC] V26a crashes if Thaumcraft isn't installed

### ISSUE THREAD

**Issue by wamc2017** [ReikaKalseki/Reika_Mods_Issues#2522]
Hi,

if Thaumcraft isn't present Chromaticraft v26a crashes:
https://gist.github.com/wamc2017/121ed418e55e2960c3166657556ed655

Thanks for looking into it.
Best regards
wamc

**Comment by ReikaKalseki** [comment]
`Caused by: java.lang.ClassFormatError: Illegal class name "net.minecraft.item.Item" in class file Reika/ChromatiCraft/ModInterface/ThaumCraft/ItemManipulatorFocus`

....Oops.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by accessdenied0** [comment]
[This issue seem to persist in v26b..](https://pastebin.com/TiJAmhuG). Or I do something wrong. (Or a different mod does something wrong)

**Comment by wamc2017** [comment]
I guess this happens for you, because of Minefactory Reloadeds Thaumcraft Compatibility. (Does it work without MFR and it's dependencies like CorhCORE?)

**Comment by accessdenied0** [comment]
Good suggestion, but to remove MFR, sadly didn't fix it... and to remove CofhCore is like to remove Thermal expansion... no idea but not a big fan to try that out, because I would love to keep that in my pack...
But generally I agree, it might be some mod who provides enough TC-API to crash the compat of Chromaticraft...
